name: Update Korea Links

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC 00:00运行
  workflow_dispatch:     # 允许手动触发

jobs:
  update-links:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run update script
      run: python update_kbs_links.py
    
    - name: Commit and push if changed
      id: commit
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add Korea.m3u
        if ! git diff --quiet && ! git diff --staged --quiet; then
          git commit -m "自动更新: 更新KBS和MBN播放链接"
          git push
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Get current date
      id: date
      if: steps.commit.outputs.changes == 'true'
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
    
    - name: Create Release
      if: steps.commit.outputs.changes == 'true'
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.date.outputs.date }}
        tag_name: v${{ steps.date.outputs.date }}
        files: Korea.m3u
        body: |
          自动更新发布 - ${{ steps.date.outputs.date }}
          
          此版本包含最新的KBS和MBN播放链接更新。
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}