name: Update Korea Links

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC 00:00运行
  workflow_dispatch:     # 允许手动触发

jobs:
  update-links:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run update script
      run: python update_korea_links.py
    
    - name: Commit and push if changed
      id: commit
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        # 保存未提交的更改
        git stash
        # 先拉取最新代码
        git pull origin main --rebase
        # 恢复未提交的更改
        git stash pop
        # 添加所有变更
        git add -A
        # 检查是否有变更
        if ! git diff --cached --quiet; then
          git commit -m "自动更新: 更新韩国频道播放链接"
          # 再次拉取并使用rebase策略
          git pull origin main --rebase
          git push
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "No changes detected"
          echo "changes=false" >> $GITHUB_OUTPUT
        fi